# Generated by Django 5.1.6 on 2026-09-08 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('discount_price', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('cover_image', models.URLField(blank=True, max_length=500, verbose_name='تصویر جلد')),
                ('level', models.CharField(choices=[('مقدماتی', 'مقدماتی'), ('پیشرفته', 'پیشرفته'), ('تخصصی', 'تخصصی')], default='مقدماتی', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='مجموع ساعت')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='شماره گواهی')),
                ('qr_code_hash', models.CharField(max_length=255, verbose_name='هش QR')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='academy.course')),
            ],
            options={
                'verbose_name': 'گواهی\u200cنامه',
                'verbose_name_plural': 'گواهی\u200cنامه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_title', models.CharField(max_length=255, verbose_name='عنوان سرفصل')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='آدرس ویدیو')),
                ('pdf_attachment', models.URLField(blank=True, max_length=500, verbose_name='فایل پیوست')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='مدت (دقیقه)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academy.course')),
            ],
            options={
                'verbose_name': 'سرفصل',
                'verbose_name_plural': 'سرفصل\u200cها',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.coursechapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='academy.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشرفت دوره',
                'verbose_name_plural': 'پیشرفت دوره\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
                ('amount_paid', models.BigIntegerField(default=0, verbose_name='مبلغ پرداختی')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=10)),
                ('discount_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='academy.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'is_free'], name='academy_cou_level_c1ca9d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='academy_cer_certifi_0ff74b_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_certificate'),
        ),
        migrations.AddIndex(
            model_name='coursechapter',
            index=models.Index(fields=['course', 'sort_order'], name='academy_cou_course__223d47_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.UniqueConstraint(fields=('user', 'chapter'), name='uniq_chapter_progress'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'payment_status'], name='academy_ord_user_id_a09d90_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_status', 'paid')), fields=('user', 'course'), name='uniq_paid_course'),
        ),
    ]
