# Generated by Django 5.1.6 on 2026-09-08 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('video_url', models.URLField(max_length=500, verbose_name='آدرس فیلم')),
                ('thumbnail', models.URLField(blank=True, max_length=500, verbose_name='تصویر بندانگشتی')),
                ('body_part', models.CharField(choices=[('کمر', 'کمر'), ('گردن', 'گردن'), ('زانو', 'زانو'), ('شانه', 'شانه'), ('مچ پا', 'مچ پا'), ('لگن', 'لگن')], max_length=20)),
                ('injury_type', models.CharField(choices=[('دیسک', 'دیسک'), ('آرتروز', 'آرتروز'), ('کشیدگی', 'کشیدگی'), ('شکستگی', 'شکستگی'), ('بعد از جراحی', 'بعد از جراحی')], max_length=20)),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='مدت (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فیلم آموزشی',
                'verbose_name_plural': 'فیلم\u200cهای آموزشی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(verbose_name='سررسید')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('done_date', models.DateTimeField(blank=True, null=True)),
                ('progress_note', models.TextField(blank=True, verbose_name='یادداشت بیمار')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_videos', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='videos.video')),
            ],
            options={
                'verbose_name': 'تجویز فیلم',
                'verbose_name_plural': 'تجویز فیلم\u200cها',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['body_part', 'injury_type'], name='videos_vide_body_pa_77f571_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprescription',
            index=models.Index(fields=['patient', 'video'], name='videos_pati_patient_6ec554_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientprescription',
            constraint=models.UniqueConstraint(fields=('patient', 'video', 'doctor'), name='uniq_prescription'),
        ),
    ]
