# Generated by Django 5.1.6 on 2026-09-08 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('لیزر', 'لیزر'), ('تکار', 'تکار'), ('طب سوزنی', 'طب سوزنی'), ('ورزش درمانی', 'ورزش درمانی'), ('معاینه عمومی', 'معاینه عمومی')], max_length=30)),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('completed', 'انجام شده'), ('canceled_by_patient', 'لغو توسط بیمار'), ('canceled_by_admin', 'لغو توسط مدیریت'), ('no_show', 'عدم حضور')], default='pending', max_length=30)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['appointment_date', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'appointment_date', 'start_time'], name='appointment_doctor__37294e_idx'), models.Index(fields=['patient', 'status'], name='appointment_patient_44acdc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('doctor', 'appointment_date', 'start_time'), name='uniq_active_slot')],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')])),
                ('start_work', models.TimeField(verbose_name='شروع کار')),
                ('end_work', models.TimeField(verbose_name='پایان کار')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='شروع استراحت')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='پایان استراحت')),
                ('session_duration', models.SmallIntegerField(choices=[(15, 15), (30, 30)], default=30, verbose_name='مدت هر نوبت (دقیقه)')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شیفت پزشک',
                'verbose_name_plural': 'شیفت\u200cهای پزشکان',
                'indexes': [models.Index(fields=['doctor', 'day_of_week'], name='appointment_doctor__c1bf72_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'day_of_week'), name='uniq_doctor_day')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'indexes': [models.Index(fields=['doctor', 'date'], name='appointment_doctor__7e613a_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date'), name='uniq_holiday'), models.UniqueConstraint(condition=models.Q(('doctor__isnull', True)), fields=('date',), name='uniq_general_holiday')],
            },
        ),
    ]
