# Generated by Django — theme, branding uploads, SiteContent, MediaAsset.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="theme",
            field=models.JSONField(blank=True, default=dict, verbose_name="تم"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="branding/", verbose_name="لوگو"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="logo_alt_text",
            field=models.CharField(blank=True, max_length=120, verbose_name="متن جایگزین لوگو"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="branding/", verbose_name="فاوآیکون"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="og_image",
            field=models.ImageField(blank=True, null=True, upload_to="branding/", verbose_name="تصویر اشتراک‌گذاری"),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.ImageField(upload_to="assets/", verbose_name="فایل")),
                ("title", models.CharField(blank=True, max_length=120, verbose_name="عنوان")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "رسانه",
                "verbose_name_plural": "رسانه‌ها",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="کلید")),
                ("data", models.JSONField(blank=True, default=dict, verbose_name="محتوا")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "محتوای قابل ویرایش",
                "verbose_name_plural": "محتواهای قابل ویرایش",
            },
        ),
    ]
