# Generated by Django 5.1.6 on 2026-09-29 15:28

import siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_theme_and_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='آیکون مرورگر — ۳۲×۳۲ یا ۱۸۰×۱۸۰ PNG', null=True, upload_to='branding/', verbose_name='فاوآیکون'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='لوگوی سایت — به\u200cجای علامت «ف» نمایش داده می\u200cشود', null=True, upload_to='branding/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='تصویری که در شبکه\u200cهای اجتماعی هنگام اشتراک لینک نمایش داده می\u200cشود', null=True, upload_to='branding/', verbose_name='تصویر اشتراک\u200cگذاری'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='theme',
            field=models.JSONField(blank=True, default=siteconfig.models._default_theme, verbose_name='تم'),
        ),
    ]
