# Generated by Django 5.1.6 on 2026-09-29 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_alter_sitesetting_favicon_alter_sitesetting_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
