# Generated by Django 5.1.6 on 2026-09-29 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_alter_mediaasset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='نام خدمت')),
                ('short_desc', models.CharField(blank=True, max_length=200, verbose_name='توضیح کوتاه (کارت خانه)')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کامل')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='آدرس تصویر (اختیاری)')),
                ('icon', models.CharField(blank=True, default='Sparkles', max_length=40, verbose_name='نام آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, help_text='از کتابخانه رسانه انتخاب می\u200cشود؛ خالی = آیکون پیش\u200cفرض', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='siteconfig.mediaasset', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
