# Generated by Django 5.1.6 on 2026-09-08 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=500, unique=True, verbose_name='لینک اصلی')),
                ('title_fa', models.CharField(max_length=500, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='عنوان اصلی')),
                ('summary_fa', models.TextField(blank=True, verbose_name='چکیده فارسی')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='تصویر')),
                ('category', models.CharField(choices=[('تکنولوژی روز', 'تکنولوژی روز'), ('تحقیقات بالینی', 'تحقیقات بالینی'), ('همایش\u200cها', 'همایش\u200cها'), ('متدهای نوین', 'متدهای نوین')], default='تحقیقات بالینی', max_length=30)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='news_newsfe_categor_1004a2_idx')],
            },
        ),
    ]
